-- =========================================================
-- KATTAMARAM - CONTROLE DE ESTOQUE
-- Banco: Supabase / PostgreSQL
-- Fluxo: Entrada -> Container -> Transferência -> Barco
-- =========================================================

create extension if not exists pgcrypto;

-- ---------- TABELAS ----------
create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category_id uuid references public.categories(id) on delete set null,
  unit text not null default 'UN',
  minimum_stock numeric(14,3) not null default 0 check (minimum_stock >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.locations (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  type text not null check (type in ('container','boat','other')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.inventory (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  location_id uuid not null references public.locations(id) on delete cascade,
  quantity numeric(14,3) not null default 0 check (quantity >= 0),
  updated_at timestamptz not null default now(),
  unique(product_id, location_id)
);

create table if not exists public.stock_entries (
  id bigint generated by default as identity primary key,
  entry_date date not null default current_date,
  invoice_number text,
  invoice_file text,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.stock_entry_items (
  id bigint generated by default as identity primary key,
  entry_id bigint not null references public.stock_entries(id) on delete cascade,
  product_id uuid not null references public.products(id),
  quantity numeric(14,3) not null check (quantity > 0),
  unit text not null default 'UN',
  created_at timestamptz not null default now()
);

create table if not exists public.transfers (
  id bigint generated by default as identity primary key,
  from_location_id uuid not null references public.locations(id),
  to_location_id uuid not null references public.locations(id),
  transfer_date timestamptz not null default now(),
  notes text,
  created_at timestamptz not null default now(),
  check (from_location_id <> to_location_id)
);

create table if not exists public.transfer_items (
  id bigint generated by default as identity primary key,
  transfer_id bigint not null references public.transfers(id) on delete cascade,
  product_id uuid not null references public.products(id),
  quantity numeric(14,3) not null check (quantity > 0),
  unit text not null default 'UN'
);

create table if not exists public.stock_movements (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products(id),
  location_id uuid not null references public.locations(id),
  movement_type text not null check (
    movement_type in ('ENTRY','TRANSFER_OUT','TRANSFER_IN','ADJUSTMENT','CONSUMPTION','LOSS')
  ),
  quantity numeric(14,3) not null,
  reference_type text,
  reference_id text,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists idx_inventory_product on public.inventory(product_id);
create index if not exists idx_inventory_location on public.inventory(location_id);
create index if not exists idx_movements_product on public.stock_movements(product_id);
create index if not exists idx_movements_created on public.stock_movements(created_at desc);
create index if not exists idx_entry_items_entry on public.stock_entry_items(entry_id);
create index if not exists idx_transfer_items_transfer on public.transfer_items(transfer_id);

-- ---------- DADOS INICIAIS ----------
insert into public.categories (name) values
  ('Bebidas'),
  ('Alimentos'),
  ('Congelados'),
  ('Limpeza'),
  ('Descartáveis'),
  ('Manutenção'),
  ('Outros')
on conflict (name) do nothing;

insert into public.locations (name, type) values
  ('Container', 'container'),
  ('Kattamaram II', 'boat')
on conflict (name) do nothing;

-- ---------- FUNÇÃO AUXILIAR ----------
create or replace function public.get_location_id(p_name text)
returns uuid
language sql
stable
as $$
  select id from public.locations where name = p_name and active = true limit 1;
$$;

-- ---------- ENTRADA DE ITEM NO CONTAINER ----------
create or replace function public.add_entry_item(
  p_entry_id bigint,
  p_product_id uuid,
  p_quantity numeric,
  p_unit text default 'UN'
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_container uuid;
begin
  if p_quantity <= 0 then
    raise exception 'Quantidade deve ser maior que zero';
  end if;

  v_container := public.get_location_id('Container');
  if v_container is null then
    raise exception 'Local Container não encontrado';
  end if;

  insert into public.stock_entry_items(entry_id, product_id, quantity, unit)
  values (p_entry_id, p_product_id, p_quantity, p_unit);

  insert into public.inventory(product_id, location_id, quantity, updated_at)
  values (p_product_id, v_container, p_quantity, now())
  on conflict (product_id, location_id)
  do update set quantity = public.inventory.quantity + excluded.quantity,
                updated_at = now();

  insert into public.stock_movements(
    product_id, location_id, movement_type, quantity,
    reference_type, reference_id, notes
  )
  values (
    p_product_id, v_container, 'ENTRY', p_quantity,
    'stock_entry', p_entry_id::text, 'Entrada de mercadoria no Container'
  );
end;
$$;

-- ---------- TRANSFERÊNCIA CONTAINER -> BARCO ----------
create or replace function public.transfer_container_to_boat(
  p_product_id uuid,
  p_quantity numeric,
  p_notes text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_container uuid;
  v_boat uuid;
  v_available numeric;
  v_transfer_id bigint;
  v_unit text;
begin
  if p_quantity <= 0 then
    raise exception 'Quantidade deve ser maior que zero';
  end if;

  v_container := public.get_location_id('Container');
  v_boat := public.get_location_id('Kattamaram II');

  if v_container is null or v_boat is null then
    raise exception 'Locais de estoque não encontrados';
  end if;

  select quantity into v_available
  from public.inventory
  where product_id = p_product_id
    and location_id = v_container
  for update;

  if coalesce(v_available, 0) < p_quantity then
    raise exception 'Estoque insuficiente no Container. Disponível: %', coalesce(v_available,0);
  end if;

  select unit into v_unit from public.products where id = p_product_id;
  if v_unit is null then
    raise exception 'Produto não encontrado';
  end if;

  insert into public.transfers(from_location_id, to_location_id, notes)
  values (v_container, v_boat, p_notes)
  returning id into v_transfer_id;

  insert into public.transfer_items(transfer_id, product_id, quantity, unit)
  values (v_transfer_id, p_product_id, p_quantity, v_unit);

  update public.inventory
  set quantity = quantity - p_quantity, updated_at = now()
  where product_id = p_product_id and location_id = v_container;

  insert into public.inventory(product_id, location_id, quantity, updated_at)
  values (p_product_id, v_boat, p_quantity, now())
  on conflict (product_id, location_id)
  do update set quantity = public.inventory.quantity + excluded.quantity,
                updated_at = now();

  insert into public.stock_movements(
    product_id, location_id, movement_type, quantity,
    reference_type, reference_id, notes
  )
  values
    (p_product_id, v_container, 'TRANSFER_OUT', -p_quantity,
     'transfer', v_transfer_id::text, p_notes),
    (p_product_id, v_boat, 'TRANSFER_IN', p_quantity,
     'transfer', v_transfer_id::text, p_notes);

  return v_transfer_id;
end;
$$;

-- ---------- TRIGGERS DE updated_at ----------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists inventory_set_updated_at on public.inventory;
create trigger inventory_set_updated_at
before update on public.inventory
for each row execute function public.set_updated_at();

-- ---------- RLS ----------
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.locations enable row level security;
alter table public.inventory enable row level security;
alter table public.stock_entries enable row level security;
alter table public.stock_entry_items enable row level security;
alter table public.transfers enable row level security;
alter table public.transfer_items enable row level security;
alter table public.stock_movements enable row level security;

-- Cenário solicitado: sem login.
-- Estas políticas permitem leitura/escrita pela chave pública.
-- Para produção com dados reais, recomenda-se ativar autenticação e restringir as policies.

drop policy if exists "public read categories" on public.categories;
create policy "public read categories" on public.categories for select to anon, authenticated using (true);

drop policy if exists "public write categories" on public.categories;
create policy "public write categories" on public.categories for insert to anon, authenticated with check (true);

drop policy if exists "public read products" on public.products;
create policy "public read products" on public.products for select to anon, authenticated using (true);

drop policy if exists "public write products" on public.products;
create policy "public write products" on public.products for insert to anon, authenticated with check (true);

drop policy if exists "public read locations" on public.locations;
create policy "public read locations" on public.locations for select to anon, authenticated using (true);

drop policy if exists "public read inventory" on public.inventory;
create policy "public read inventory" on public.inventory for select to anon, authenticated using (true);

drop policy if exists "public read entries" on public.stock_entries;
create policy "public read entries" on public.stock_entries for select to anon, authenticated using (true);

drop policy if exists "public write entries" on public.stock_entries;
create policy "public write entries" on public.stock_entries for insert to anon, authenticated with check (true);

drop policy if exists "public read entry items" on public.stock_entry_items;
create policy "public read entry items" on public.stock_entry_items for select to anon, authenticated using (true);

drop policy if exists "public write entry items" on public.stock_entry_items;
create policy "public write entry items" on public.stock_entry_items for insert to anon, authenticated with check (true);

drop policy if exists "public read transfers" on public.transfers;
create policy "public read transfers" on public.transfers for select to anon, authenticated using (true);

drop policy if exists "public write transfers" on public.transfers;
create policy "public write transfers" on public.transfers for insert to anon, authenticated with check (true);

drop policy if exists "public read transfer items" on public.transfer_items;
create policy "public read transfer items" on public.transfer_items for select to anon, authenticated using (true);

drop policy if exists "public write transfer items" on public.transfer_items;
create policy "public write transfer items" on public.transfer_items for insert to anon, authenticated with check (true);

drop policy if exists "public read movements" on public.stock_movements;
create policy "public read movements" on public.stock_movements for select to anon, authenticated using (true);

-- ---------- STORAGE ----------
insert into storage.buckets (id, name, public)
values ('invoices', 'invoices', false)
on conflict (id) do nothing;

drop policy if exists "public upload invoices" on storage.objects;
create policy "public upload invoices"
on storage.objects for insert to anon, authenticated
with check (bucket_id = 'invoices');

drop policy if exists "public read invoices" on storage.objects;
create policy "public read invoices"
on storage.objects for select to anon, authenticated
using (bucket_id = 'invoices');

-- =========================================================
-- FIM
-- =========================================================
