const {createClient}=supabase,db=createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);let products=[],cats=[];const $=s=>document.querySelector(s),money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function init(){let {data:{session}}=await db.auth.getSession();session?showApp():showLogin()}function showLogin(){$('#login').classList.remove('hidden');$('#app').classList.add('hidden')}function showApp(){$('#login').classList.add('hidden');$('#app').classList.remove('hidden');load()}$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';let {error}=await db.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});if(error)$('#loginError').textContent=error.message;else showApp()};$('#logout').onclick=$('#mlogout').onclick=async()=>{await db.auth.signOut();showLogin()};document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>view(b.dataset.v));function view(id){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));$('#'+id).classList.remove('hidden')}
async function load(){let c=await db.from('categories').select('*').order('position'),p=await db.from('products').select('*,categories(name)').order('position');if(c.error||p.error){alert((c.error||p.error).message);return}cats=c.data||[];products=p.data||[];$('#sp').textContent=products.filter(x=>x.active).length;$('#sc').textContent=cats.filter(x=>x.active).length;$('#sf').textContent=products.filter(x=>x.active&&x.featured).length;fillCats();drawProducts();drawCats()}
function fillCats(){const active=cats.filter(x=>x.active);$('#pcat').innerHTML=active.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');$('#filterCat').innerHTML='<option value="">Todas as categorias</option>'+cats.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}
function drawProducts(){let q=($('#search').value||'').toLowerCase(),fc=$('#filterCat').value;let list=products.filter(p=>(!q||p.name.toLowerCase().includes(q))&&(!fc||String(p.category_id)===fc));$('#rows').innerHTML=list.map(p=>{let n=Array.isArray(p.options)?p.options.length:0;return `<tr><td><img src="${p.image_url||'images/placeholder.svg'}"><strong>${esc(p.name)}</strong><small>${esc(p.description||'')}</small></td><td>${esc(p.categories?.name||'—')}</td><td>${money(p.price)}</td><td>${n?`<span class="optionBadge">${n} ${n===1?'opção':'opções'}</span>`:'—'}</td><td><span class="badge ${p.active?'':'off'}">${p.active?'ATIVO':'OCULTO'}</span></td><td><button class="edit" onclick="openProduct(${p.id})">Editar</button> <button class="edit danger" onclick="delProduct(${p.id})">Excluir</button></td></tr>`}).join('')||'<tr><td colspan="6">Nenhum produto.</td></tr>'}
function drawCats(){$('#catGrid').innerHTML=cats.map(c=>`<div class="catCard"><div class="catIcon">${c.icon||'•'}</div><h3>${esc(c.name)}</h3><div>${c.active?'Ativa':'Oculta'} • ordem ${c.position||0}</div><button onclick="openCategory(${c.id})">Editar</button><button onclick="delCat(${c.id})">Excluir</button></div>`).join('')}
function optionTemplate(o={},i=0){return `<div class="optionItem" data-option><div class="optionHead"><strong>Opção ${i+1}</strong><button type="button" class="removeOption" onclick="this.closest('[data-option]').remove()">×</button></div><div class="formGrid"><label>Nome<input data-oname value="${esc(o.name||'')}" placeholder="Ex.: Morango"></label><label>Preço adicional<input data-oprice type="number" step="0.01" value="${o.price==null?'':o.price}" placeholder="0,00"></label></div><label>Descrição<input data-odesc value="${esc(o.description||'')}" placeholder="Ex.: com frutas frescas"></label><div class="optionImage"><label>Foto da opção<input data-ofile type="file" accept="image/*"></label>${o.image_url?`<img src="${o.image_url}" alt="">`:''}<input type="hidden" data-oimage value="${esc(o.image_url||'')}"></div></div>`}
function addOption(o={}){$('#optionsList').insertAdjacentHTML('beforeend',optionTemplate(o,$('#optionsList').children.length));reindexOptions()}
function reindexOptions(){[...document.querySelectorAll('[data-option]')].forEach((el,i)=>el.querySelector('.optionHead strong').textContent=`Opção ${i+1}`)}
function collectOptions(){return [...document.querySelectorAll('[data-option]')].map(el=>({name:el.querySelector('[data-oname]').value.trim(),price:el.querySelector('[data-oprice]').value===''?null:Number(el.querySelector('[data-oprice]').value),description:el.querySelector('[data-odesc]').value.trim()||null,image_url:el.querySelector('[data-oimage]').value||null,file:el.querySelector('[data-ofile]').files[0]||null})).filter(o=>o.name)}
async function uploadFile(file){let path=`products/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;let u=await db.storage.from('product-images').upload(path,file,{contentType:file.type});if(u.error)throw u.error;return db.storage.from('product-images').getPublicUrl(path).data.publicUrl}
function openProduct(id){$('#perr').textContent='';$('#saveState').textContent='';$('#productForm').reset();$('#pid').value='';$('#ptitle').textContent='Novo produto';$('#pactive').checked=true;$('#oldimg').innerHTML='';$('#optionsList').innerHTML='';if(id){let p=products.find(x=>x.id===id);$('#ptitle').textContent='Editar produto';$('#pid').value=p.id;$('#pname').value=p.name;$('#pcat').value=p.category_id;$('#pprice').value=p.price;$('#ppos').value=p.position||0;$('#pdesc').value=p.description||'';$('#pfeatured').checked=!!p.featured;$('#pactive').checked=!!p.active;if(p.image_url)$('#oldimg').innerHTML=`<img src="${p.image_url}" style="max-width:130px;border-radius:8px" alt="">`;(Array.isArray(p.options)?p.options:[]).forEach(o=>addOption(o))}$('#pmodal').classList.add('show')}
function closeProduct(){$('#pmodal').classList.remove('show')}
$('#productForm').onsubmit=async e=>{e.preventDefault();$('#perr').textContent='';$('#saveState').textContent='Salvando...';let id=$('#pid').value,old=products.find(p=>String(p.id)===id),url=old?.image_url||null,file=$('#pfile').files[0];try{if(file)url=await uploadFile(file);let opts=collectOptions();for(const o of opts){if(o.file){o.image_url=await uploadFile(o.file)}delete o.file}let payload={category_id:+$('#pcat').value,name:$('#pname').value.trim(),description:$('#pdesc').value.trim()||null,price:+$('#pprice').value,image_url:url,featured:$('#pfeatured').checked,active:$('#pactive').checked,position:+$('#ppos').value||0,options:opts,updated_at:new Date().toISOString()};let r=id?await db.from('products').update(payload).eq('id',id):await db.from('products').insert(payload);if(r.error)throw r.error;$('#saveState').textContent='Salvo ✓';setTimeout(()=>{closeProduct();load()},350)}catch(x){$('#saveState').textContent='';$('#perr').textContent=x.message||String(x)}};
async function delProduct(id){if(confirm('Excluir este produto?')){let r=await db.from('products').delete().eq('id',id);if(r.error)alert(r.error.message);else load()}}
function openCategory(id){$('#categoryForm').reset();$('#cid').value='';$('#cactive').checked=true;$('#cerr').textContent='';if(id){let c=cats.find(x=>x.id===id);$('#cid').value=c.id;$('#cname').value=c.name;$('#cicon').value=c.icon||'';$('#cpos').value=c.position||0;$('#cactive').checked=c.active}$('#cmodal').classList.add('show')}function closeCategory(){$('#cmodal').classList.remove('show')}$('#categoryForm').onsubmit=async e=>{e.preventDefault();let id=$('#cid').value,p={name:$('#cname').value.trim(),icon:$('#cicon').value.trim(),position:+$('#cpos').value||0,active:$('#cactive').checked},r=id?await db.from('categories').update(p).eq('id',id):await db.from('categories').insert(p);if(r.error)$('#cerr').textContent=r.error.message;else{closeCategory();load()}};async function delCat(id){if(confirm('Excluir categoria? Produtos ligados a ela também serão excluídos pela regra atual do banco.')){let r=await db.from('categories').delete().eq('id',id);if(r.error)alert(r.error.message);else load()}}init();
